name: Test Policies One by One

on:
  workflow_dispatch:
    inputs:
      policy_file:
        description: 'Policy file to test (e.g., s3-createbucket.yml)'
        required: true
        type: string
        default: 's3-createbucket.yml'
      test_action:
        description: 'Test action'
        required: true
        type: choice
        options:
          - validate-only
          - dry-run
          - deploy-test
        default: 'validate-only'

env:
  AWS_REGION: us-east-1
  PYTHON_VERSION: "3.11"

permissions:
  id-token: write
  contents: read

jobs:
  test-policy:
    name: Test Policy - ${{ inputs.policy_file }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActions-CloudCustodian-Role
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Cloud Custodian
        run: |
          pip install c7n c7n-org pyyaml boto3
          custodian version
      
      # ====================================================================
      # STEP 1: Validate Policy Syntax
      # ====================================================================
      - name: Validate policy syntax
        run: |
          echo "🔍 Validating policy: ${{ inputs.policy_file }}"
          
          POLICY_PATH="policies/${{ inputs.policy_file }}"
          
          if [ ! -f "$POLICY_PATH" ]; then
            echo "❌ Policy file not found: $POLICY_PATH"
            exit 1
          fi
          
          # Validate YAML syntax
          python -c "import yaml; yaml.safe_load(open('$POLICY_PATH'))"
          echo "✓ YAML syntax valid"
          
          # Validate Cloud Custodian policy
          custodian validate "$POLICY_PATH"
          echo "✓ Policy validation successful"
      
      # ====================================================================
      # STEP 2: Dry Run (if selected)
      # ====================================================================
      - name: Dry run policy
        if: inputs.test_action == 'dry-run' || inputs.test_action == 'deploy-test'
        run: |
          echo "🧪 Running policy in dry-run mode..."
          
          POLICY_PATH="policies/${{ inputs.policy_file }}"
          OUTPUT_DIR="test-output/$(date +%Y%m%d-%H%M%S)"
          
          mkdir -p "$OUTPUT_DIR"
          
          # Run in dry-run mode (no actions executed)
          custodian run \
            -s "$OUTPUT_DIR" \
            --region ${{ env.AWS_REGION }} \
            --dryrun \
            "$POLICY_PATH"
          
          echo "📊 Dry-run results:"
          ls -la "$OUTPUT_DIR"
          
          # Display resources.json if exists
          if [ -f "$OUTPUT_DIR"/*/resources.json ]; then
            echo "Resources matched:"
            cat "$OUTPUT_DIR"/*/resources.json | jq -r '.[] | .Name // .id // .Id' | head -20
          fi
      
      # ====================================================================
      # STEP 3: Upload Policy to S3 (if deploying test)
      # ====================================================================
      - name: Upload policy to S3 for testing
        if: inputs.test_action == 'deploy-test'
        run: |
          echo "📦 Uploading policy to S3..."
          
          # Get S3 bucket name from CloudFormation or use environment variable
          S3_BUCKET="${{ secrets.CUSTODIAN_BUCKET_NAME }}"
          
          if [ -z "$S3_BUCKET" ]; then
            # Try to find bucket by name pattern
            S3_BUCKET=$(aws s3api list-buckets --query "Buckets[?contains(Name, 'custodian')].Name | [0]" --output text)
          fi
          
          if [ -z "$S3_BUCKET" ] || [ "$S3_BUCKET" == "None" ]; then
            echo "❌ ERROR: Could not find S3 bucket"
            echo "Please set CUSTODIAN_BUCKET_NAME secret in GitHub or deploy infrastructure first"
            exit 1
          fi
          
          echo "Using S3 bucket: $S3_BUCKET"
          
          POLICY_PATH="policies/${{ inputs.policy_file }}"
          
          aws s3 cp "$POLICY_PATH" "s3://${S3_BUCKET}/policies/${{ inputs.policy_file }}"
          
          echo "✓ Policy uploaded to: s3://${S3_BUCKET}/policies/${{ inputs.policy_file }}"
      
      # ====================================================================
      # STEP 4: Update Policy Mappings (if needed)
      # ====================================================================
      - name: Update policy mappings
        if: inputs.test_action == 'deploy-test'
        run: |
          echo "📝 Checking policy mappings..."
          
          # Get S3 bucket name
          S3_BUCKET="${{ secrets.CUSTODIAN_BUCKET_NAME }}"
          
          if [ -z "$S3_BUCKET" ]; then
            S3_BUCKET=$(aws s3api list-buckets --query "Buckets[?contains(Name, 'custodian')].Name | [0]" --output text)
          fi
          
          echo "Using S3 bucket: $S3_BUCKET"
          
          # Download current mappings (note: it's .json not .yml)
          aws s3 cp "s3://${S3_BUCKET}/config/policy-mappings.json" /tmp/policy-mappings.json || true
          
          if [ -f /tmp/policy-mappings.json ]; then
            echo "✓ Current policy mappings downloaded"
            cat /tmp/policy-mappings.json
          else
            echo "⚠️ No existing policy mappings found"
          fi
          
          echo ""
          echo "ℹ️ To add this policy to mappings, update config/policy-mappings.json"
      
      # ====================================================================
      # STEP 5: Trigger Test Event (if deploying test)
      # ====================================================================
      - name: Trigger test event
        if: inputs.test_action == 'deploy-test'
        run: |
          echo "🎯 Triggering test event..."
          
          # Determine event type based on policy file name
          if [[ "${{ inputs.policy_file }}" == *"s3"* ]]; then
            echo "Creating test S3 bucket..."
            
            TEST_BUCKET="test-custodian-$(date +%s)"
            
            # Create bucket (this will trigger EventBridge)
            aws s3api create-bucket \
              --bucket "$TEST_BUCKET" \
              --region ${{ env.AWS_REGION }}
            
            echo "✓ Test bucket created: $TEST_BUCKET"
            echo "⏳ Wait 30 seconds for event processing..."
            sleep 30
            
            # Check if bucket still exists (should be deleted by policy)
            if aws s3api head-bucket --bucket "$TEST_BUCKET" 2>/dev/null; then
              echo "⚠️ Test bucket still exists (policy may not have run yet)"
            else
              echo "✅ Test bucket was deleted by policy!"
            fi
            
          elif [[ "${{ inputs.policy_file }}" == *"ec2"* ]]; then
            echo "ℹ️ EC2 test requires manual RunInstances action"
            echo "Policy will trigger on next EC2 instance creation"
            
          else
            echo "⚠️ Unknown policy type, skipping test event"
          fi
      
      # ====================================================================
      # STEP 6: Check Logs
      # ====================================================================
      - name: Check execution logs
        if: inputs.test_action == 'deploy-test'
        run: |
          echo "📋 Checking Lambda and ECS logs..."
          
          # Get Lambda function name
          LAMBDA_FUNCTION="${{ secrets.LAMBDA_FUNCTION_NAME }}"
          
          if [ -z "$LAMBDA_FUNCTION" ]; then
            LAMBDA_FUNCTION=$(aws lambda list-functions --query "Functions[?contains(FunctionName, 'custodian')].FunctionName | [0]" --output text --region ${{ env.AWS_REGION }})
          fi
          
          echo "Using Lambda function: $LAMBDA_FUNCTION"
          
          # Get recent Lambda logs
          echo "Lambda Invoker logs (last 5 minutes):"
          aws logs tail "/aws/lambda/${LAMBDA_FUNCTION}" \
            --since 5m \
            --format short \
            --region ${{ env.AWS_REGION }} || true
          
          echo ""
          echo "ECS Worker logs (last 5 minutes):"
          aws logs tail "/ecs/cloud-custodian-worker" \
            --since 5m \
            --format short \
            --region ${{ env.AWS_REGION }} || true
          
          echo ""
          echo "📊 Checking ECS Service status..."
          CLUSTER_NAME="${{ secrets.ECS_CLUSTER_NAME }}"
          
          if [ -z "$CLUSTER_NAME" ]; then
            CLUSTER_NAME=$(aws ecs list-clusters --query "clusterArns[?contains(@, 'custodian')] | [0]" --output text --region ${{ env.AWS_REGION }} | awk -F'/' '{print $NF}')
          fi
          
          echo "Using ECS cluster: $CLUSTER_NAME"
          
          # Check ECS Service
          SERVICE_NAME=$(aws ecs list-services --cluster "$CLUSTER_NAME" --query "serviceArns[0]" --output text --region ${{ env.AWS_REGION }} | awk -F'/' '{print $NF}')
          
          if [ -n "$SERVICE_NAME" ] && [ "$SERVICE_NAME" != "None" ]; then
            aws ecs describe-services \
              --cluster "$CLUSTER_NAME" \
              --services "$SERVICE_NAME" \
              --query 'services[0].{desired:desiredCount,running:runningCount,pending:pendingCount}' \
              --region ${{ env.AWS_REGION }} || echo "⚠️ ECS service not found or not running"
          else
            echo "⚠️ No ECS service found in cluster"
          fi
          
          echo ""
          echo "📬 Checking SQS Queue..."
          QUEUE_NAME="${{ secrets.SQS_QUEUE_NAME }}"
          
          if [ -z "$QUEUE_NAME" ]; then
            QUEUE_NAME=$(aws sqs list-queues --query "QueueUrls[?contains(@, 'custodian')] | [0]" --output text --region ${{ env.AWS_REGION }} | awk -F'/' '{print $NF}')
          fi
          
          if [ -n "$QUEUE_NAME" ] && [ "$QUEUE_NAME" != "None" ]; then
            SQS_QUEUE_URL=$(aws sqs get-queue-url --queue-name "$QUEUE_NAME" --output text --region ${{ env.AWS_REGION }} 2>/dev/null || echo "")
            
            if [ -n "$SQS_QUEUE_URL" ]; then
              aws sqs get-queue-attributes \
                --queue-url "$SQS_QUEUE_URL" \
                --attribute-names ApproximateNumberOfMessages ApproximateNumberOfMessagesNotVisible \
                --region ${{ env.AWS_REGION }}
            else
              echo "⚠️ SQS queue URL not found"
            fi
          else
            echo "⚠️ SQS queue not found"
          fi
      
      # ====================================================================
      # STEP 7: Generate Test Report
      # ====================================================================
      - name: Generate test report
        if: always()
        run: |
          cat <<EOF > test-report.md
          ## 🧪 Policy Test Report
          
          **Policy:** \`${{ inputs.policy_file }}\`
          **Test Action:** \`${{ inputs.test_action }}\`
          **Test Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          **Triggered by:** ${{ github.actor }}
          
          ### Test Results
          
          EOF
          
          if [ "${{ inputs.test_action }}" == "validate-only" ]; then
            echo "✅ Policy syntax validation: PASSED" >> test-report.md
          elif [ "${{ inputs.test_action }}" == "dry-run" ]; then
            echo "✅ Policy syntax validation: PASSED" >> test-report.md
            echo "✅ Dry-run execution: COMPLETED" >> test-report.md
          elif [ "${{ inputs.test_action }}" == "deploy-test" ]; then
            echo "✅ Policy deployed to S3" >> test-report.md
            echo "✅ Test event triggered" >> test-report.md
            echo "✅ Check CloudWatch Logs for execution details" >> test-report.md
          fi
          
          cat <<EOF >> test-report.md
          
          ### Next Steps
          
          1. Review CloudWatch Logs for Lambda and ECS
          2. Check S3 bucket outputs
          3. Verify SQS queue metrics (should scale ECS from 0 when messages arrive)
          4. Monitor ECS Service scaling (0 → N tasks based on queue depth)
          5. Verify ECS tasks scale back to 0 after queue is empty
          6. Monitor CloudWatch metrics for policy execution
          7. Add policy to policy-mappings.json if test successful
          
          ### Architecture Flow
          
          1. EventBridge detects security event
          2. Lambda parses event and selects policy
          3. Lambda sends message to SQS queue
          4. Auto-scaling detects messages in queue
          5. ECS Service scales from 0 to N tasks (based on 5 messages per task)
          6. Fargate tasks process messages and execute policies
          7. After ~60 seconds of no messages, tasks exit gracefully
          8. ECS Service scales back to 0 tasks (no cost when idle)
          
          ### Useful AWS Console Links
          
          - [Lambda Function Logs](https://console.aws.amazon.com/cloudwatch/home?region=${{ env.AWS_REGION }}#logsV2:log-groups/log-group/\$252Faws\$252Flambda\$252Fcloud-custodian-invoker)
          - [ECS Worker Logs](https://console.aws.amazon.com/cloudwatch/home?region=${{ env.AWS_REGION }}#logsV2:log-groups/log-group/\$252Fecs\$252Fcloud-custodian-worker)
          - [SQS Queue](https://console.aws.amazon.com/sqs/v2/home?region=${{ env.AWS_REGION }})
          - [EventBridge Rules](https://console.aws.amazon.com/events/home?region=${{ env.AWS_REGION }}#/rules)
          EOF
          
          cat test-report.md
          echo "✓ Test report generated"
      
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ inputs.policy_file }}
          path: |
            test-output/
            test-report.md
          retention-days: 7

# ======================================================================
# Batch Test Job - Test Multiple Policies
# ======================================================================
  batch-test-policies:
    name: Batch Test Policies
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.test_action == 'validate-only'
    
    strategy:
      matrix:
        policy:
          - s3-createbucket.yml
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Cloud Custodian
        run: |
          pip install c7n pyyaml
          custodian version
      
      - name: Validate policy
        run: |
          POLICY_PATH="policies/${{ matrix.policy }}"
          
          if [ ! -f "$POLICY_PATH" ]; then
            echo "⚠️ Policy file not found: $POLICY_PATH (skipping)"
            exit 0
          fi
          
          echo "🔍 Validating: ${{ matrix.policy }}"
          custodian validate "$POLICY_PATH"
          echo "✅ ${{ matrix.policy }} validated successfully"
